### ISSUE TITLE
Why is logic changing expectations should be avoided?

### ISSUE THREAD

**Issue by patrickbard** [gburghardt/jasmine-data_driven_tests#8]
I've been using this lib a lot lately and it helps so much to clean the test code. That's the main reason why we opted for it on the first place, since we had lot of similar tests.

But just now I realized that you pointed in the description that logic changing expectations should be avoided.

While I understand that in a general basis, I don't think is that bad in some situations. For example, a lot of things we do look like this:

    all("should ...",
        [
            [true,  false, false],
            [true,  true,  true],
            [false, true,  true],
            [false, false, true]
        ], function (foo, bar, expected) {
            // given
            scope.model = {foo: foo, bar: bar};

            // when
            var result = scope.doSomething();

            // then
            expect(result).toEqual(expected);
        }
    );

What's utterly wrong with that approach and why should I change it to something like this:

    it("should ...", function(){
        // given
        scope.model = {foo: true, bar: false};

        // when
        var result = scope.doSomething();

        // then
        expect(result).toEqual(false);
    });

    all("should ...",
        [
            [true,  true],
            [false, true],
            [false, false]
        ], function (foo, bar) {
            // given
            scope.model = {foo: foo, bar: bar};

            // when
            var result = scope.doSomething();

            // then
            expect(result).toEqual(true);
        }
    );

**Comment by gburghardt** [comment]
The main reason I recommended against changing the logic of the expectations is philosophical, not technical. It all has to do with how the specs read coupled with the best practice of having one assertion per test.

I would argue that a different assertion &mdash; even a difference in `should be true` to `should be false` should be separate tests for the sake of readability.

It is more difficult to track a data driven test in your head simply because the input data is parameterized. I've found it easier to track all this stuff when the expectations are the same for all inputs.

When you change the expectations you are essentially putting two data driven tests into one. This can be especially difficult to maintain when doing boundary testing.

However, as with all guidelines, law enforcement is not going to show up at your front door, throw a tea cozy over your head and drag you away into the night if you don't follow the guidelines. Code with tests is always better than code with no tests, and sometimes you are in a time crunch and just need to get the silly test cases in the system.

So use your best judgement.

Thanks for using it! I'm glad you find it useful.
